### ISSUE TITLE
not published on npm

### ISSUE THREAD

**Issue by juliuste** [derhuerst/vbb-entrances#2]
The `npm install vbb-entrances`, as mentioned in the installation instructions obviously doesn't work since the project isn't published on npm yet.

**Comment by derhuerst** [comment]
It seems that i left this module unfinished. In fact, it downloads & parses the entrances just fine, but my local working copy has uncommitted changes for rendering a PDF. Will publish the raw entrances to NPM.

**Comment by derhuerst** [comment]
`vbb-entrances@0.1.0` has been published.
